### ISSUE TITLE
track and display the email clients used by recipients somewhere in the admin

### ISSUE THREAD

**Issue by equivalentideas** [mlandauer/cuttlefish#194]
It would be handy to know for instance how many people are using mobile email clients, outlook etc. for the design of email templates.

**Comment by mlandauer** [comment]
In the open and click events we record the user agent which can give us that information. We used to have some functionality in there to convert that to something human readable (basically the email client name or web browser if it's a web client) but it was disabled because of performance issues. It should be relatively straightforward to add this again (after dealing with the performance issue).

**Comment by equivalentideas** [comment]
Here's mailchimps version of this display:

![screen shot 2015-01-20 at 11 27 45 am](https://cloud.githubusercontent.com/assets/1239550/5810247/85e2ad80-a097-11e4-810f-6e861cd5e453.png)

**Comment by mlandauer** [comment]
For the beginnings of this see https://cuttlefish.oaf.org.au/emails/204172 - If you open the open and click event you can see the clients used.

To make this work properly, we'll also need to detect things like gmail and hotmail correctly which should be pretty easy because they'll appear as web browsers at an email address connected to those services.

Also, we'll need to store this parsed user agent data in the database so that we can create aggregate stats like the example you gave above @equivalentideas.

**Comment by mlandauer** [comment]
There's a really really rough page that shows stats for all the apps now https://cuttlefish.oaf.org.au/clients

It doesn't show percentages or allow you to break it down by app.

**Comment by equivalentideas** [comment]
Nice one @mlandauer .

Surprising to see Apple Mail higher than Outlook!
