### ISSUE TITLE
Remove a specific address from the blacklist

### ISSUE THREAD

**Issue by henare** [mlandauer/cuttlefish#217]
If you want to remove a specific address from the blacklist you currently have to trawl through the blacklist to find it then click remove. There should be a way to search the blacklist or something.

**Comment by equivalentideas** [comment]
Just went through this process:

1. Someone emailed about not receiving our emails.
2. I thought maybe their emails are being held back.
3. I opened cuttlefish and searched for their email address.
4. On the search results I saw the emails to them were being held back.
4. Know I wanted to know if they were being held back because the person was blacklisted, and to remove them from that list. I couldn't see a way to do that on this search results page.
5. I clicked into the latest email to look at it.
6. I looked for a way to unblacklist this person on that page (email show page).
7. I decided this is probably in the blacklist page so I navigated there via the sidebar.
8. I looked for a way to search but couldn't find any, so I instictively put the email in the search form again.
9. This took me back to the list of emails sent to the address.
10. I clicked onto another one of the person’s emails looking for a way to unblacklist them.
11. Saw none so went back to the blacklist page
12. Did a page search in the browser for the address, no luck :(
13. There's only 30 address per page so we have more than 100 pages to look through.
13. Came here.

When I need to see if a specific person is blacklisted, please help me find that person, so I can remove them and they can get emails again.

Here's a few ideas for how to enable this:

1. Have a search form on the blacklist page allowing me to look up the specific address I'm looking for
2. When I search for an email address using the app search, if the address is blacklisted, let me know at the top of the page and give me a way to remove it. This would have led me to solving my problem really quickly.
3. On an email show page for a blacklisted address, let me know that they're blacklisted and allow me to remove them.

**Comment by equivalentideas** [comment]
Currently the blacklist view is broken (see #257) so you can use the trawling method above.

**Comment by henare** [comment]
You can get to a page that allows you to remove an address from the backlist at this URL (change the email in the URL to the one you're interested in): https://cuttlefish.oaf.org.au/addresses/email@domain.com/to

**Comment by mlandauer** [comment]
And you can do a search for an email address and find it that way
