### ISSUE TITLE
Why PostgreSQL ?

### ISSUE THREAD

**Issue by extremeshok** [mlandauer/cuttlefish#252]
This project moved from MySQL to PostgreSQL

Would it not of have been better to support both and run the code with generic Open Database Connectivity (ODBC) ?

**Comment by Serkan-devel** [comment]
https://github.com/mlandauer/cuttlefish/issues/223

**Comment by mlandauer** [comment]
The original reason for moving from MySQL to PostgreSQL was because postgres does not lock everything during schema changes. Since the tables in cuttlefish can get quite large if tables are locked during migrations it can cause significant downtimes.

Having said that, everything in cuttlefish is using Rails activerecord to access the database and there's no postgres specific SQL being used as far as I'm aware. That means if you wanted to use mysql it would be an easy change.
