### ISSUE TITLE
[OAF Cuttlefish/production] NoMethodError: undefined method `subject' for nil:NilClass

### ISSUE THREAD

**Issue by mlandauer** [mlandauer/cuttlefish#257]
## Backtrace

    line 22 of [PROJECT_ROOT]/app/views/black_lists/index.html.haml: block (2 levels) in _app_views_black_lists_index_html_haml___1792557224393560556_70114678063140
    line 18 of [PROJECT_ROOT]/app/views/black_lists/index.html.haml: block in _app_views_black_lists_index_html_haml___1792557224393560556_70114678063140
    line 8 of [PROJECT_ROOT]/app/views/black_lists/index.html.haml: _app_views_black_lists_index_html_haml___1792557224393560556_70114678063140

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/41008/faults/31753851)

**Comment by equivalentideas** [comment]
I hit this when navigating through the blacklist’s pagination looking for a specific address.

https://cuttlefish.oaf.org.au/black_lists?page=60 is fine , then from https://cuttlefish.oaf.org.au/black_lists?page=63 it raises a 500 with this error.

**Comment by equivalentideas** [comment]
This error is also ocuring on this view https://cuttlefish.oaf.org.au/addresses/example@email.com/to

**Comment by equivalentideas** [comment]
This is raised when a BlackList instance is asked for its .caused_by_delivery , and the id for the delivery provided doesn't match a Delivery in the database.

**Comment by equivalentideas** [comment]
I'm not sure what the best way to deal with this bug is, so I'm just going to destroy the blacklist record for the address (as the app would if I could get to that button), which will let me fix the situation for the user I'm trying to help.

**Comment by equivalentideas** [comment]
Looking at this with @Henare , we recon this is related to the archiving task we ran a while back. The [archive function destroys deliveries](https://github.com/mlandauer/cuttlefish/blob/master/lib/archiving.rb#L32), and if you have an address that was blacklisted because of one of those deliveries, it can no longer be displayed, because of the bug above.

**Comment by equivalentideas** [comment]
[Archiving deliveries](https://github.com/mlandauer/cuttlefish/pull/270) means that it's common for deliveries that have relationships to Blacklist objects (and other objects) to be missing.

We get the error above because our view code expects the related delivery to not be Null.

An initial step could be to check whether the delivery in exists whenever we need it. Alternatively we could use the [Null Object pattern](https://robots.thoughtbot.com/design-patterns-in-the-wild-null-object) here.
