### ISSUE TITLE
Why AGPL?

### ISSUE THREAD

**Issue by coolaj86** [mlandauer/cuttlefish#265]
I always check licenses before I start using software and I try to stay away from *GPL licenses due to the various legal complications.

I'm all about open source and contributing changes, but the AGPL in particular just makes me uncomfortable.

Did you chose AGPL because you're planning on making a commercial version? I'd be happy to purchase a license for that (depending on the price, of course. $500+ is a bit out of what I'm looking to pay)?

Or would you reconsider using a more liberal license such as Apache-2 or MIT?

(I see the GPL as the DRM of the "open source" world - once you let it infect one part of your system, it can trickle all over in places you didn't expect and have troubling ramifications)

**Comment by coolaj86** [comment]
P.S. I believe the MPL also accomplishes most of the same goals of *GPL without being so restrictive about tangential works.

**Comment by coolaj86** [comment]
bump

**Comment by Serkan-devel** [comment]
Why not an MIT license?

**Comment by akuckartz** [comment]
What exact issue do those objecting to the AGPL see? It requires to publish the complete source code. Is that a problem? How?

**Comment by Serkan-devel** [comment]
Mostly due to license compatibility

`Because you have more important things to do than enriching lawyers or imposing petty restrictions on users of your code. How often have you passed up on utilizing and contributing to a great software library just because its open source license was not compatible with your own preferred <a href="http://www.opensource.org/licenses/alphabetical">flavor</a> of open source? How many precious hours of your life have you spent deliberating how to license your software or worrying about licensing compatibility with other software? You will never get those hours back,...`
(Source: http://www.opensource.org/licenses/alphabetical)

But I don't want to be harsh here, I still like this project very much.

**Comment by jspraul** [comment]
Probably because this project is in direct competition with several commercial offerings, and if it becomes good enough it could easily be the basis of a commercial service which would be highly inclined to implement differentiating features and keep them to itself.

This is already happening in this space: https://www.sentopia.net/ which was at least at one point based on https://sendy.co/ per https://news.ycombinator.com/item?id=9475056

**Comment by Serkan-devel** [comment]
@jspraul would an MPL license prevent such a thing already?

**Comment by jspraul** [comment]
Unfortunately I'm not very familiar with the MPL -- neither its purpose or how it works out in practice.

**Comment by mlandauer** [comment]
The reason it's AGPL is because of what @jspraul so clearly articulated:
> Probably because this project is in direct competition with several commercial offerings, and if it becomes good enough it could easily be the basis of a commercial service which would be highly inclined to implement differentiating features and keep them to itself.

It would be fine if a commercial provider were to use cuttlefish and support the development by adding features which are part of the open-source code. It would not be fine for a commercial provider to use cuttlefish and then add features that it keeps to itself. That would be parasitic. So, the license is there to prevent that.

**Comment by coolaj86** [comment]
So then, if by being licensed AGPL, the code is effectively being kept more to itself and getting less community... is it not self-parasitic?
