### ISSUE TITLE
Allow configurable DKIM selector

### ISSUE THREAD

**Issue by jamezpolley** [mlandauer/cuttlefish#299]
I'm running an event using the domain conference.com.au. Under that domain, I have an SSO system (which sends mail from accounts@conference.com.au as users create their account), event management software (which sends mail from event@conference.com.au) and an announcements system what sends mail on behalf of the organizers (from team@conference.com.au). Each app has its own set of administrators. I don't want the separate teams to be sharing credentials, and I want them to be able to only see mail sent from their own app.

At present, this is not possible, as each app would have to have conference.com.au as its domain, and would create a record for ```cutlefish._domainkey.conference.com.au```. 

Possible workarounds: use seperate subdomains for each app; or share the credentials between teams.

**Comment by mlandauer** [comment]
Thanks @jamezpolley for writing this use case up. This is super helpful. After reading this and thinking about it over the last day, I agree that #298 is a bit misguided. It seems that an "App" is really a way to group a set of emails together. It basically says "I want to administer these emails as a group". In your example there would be several "Apps" using the same email domain to send email from. This seems completely reasonable to me.

I think what's tricky is to figure out the best way to present this to users. Maybe it's just a question of having a different way that the DKIM records are defined so that you can have multiple ones in a single domain without them clashing? Or maybe if you have several apps in your team using the same domain then they'll automatically use the same record?

There is a second problem intertwined in your use case that of permissions. It seems you want you want to have several apps in your team with different people only having access to a subset of apps. In the current (pretty simple) security model, there's basically a team which has administrators all of which can see all the apps that are in the team.

**Comment by jamezpolley** [comment]
> There is a second problem intertwined in your use case that of permissions. It seems you want you want to have several apps in your team with different people only having access to a subset of apps. In the current (pretty simple) security model, there's basically a team which has administrators all of which can see all the apps that are in the team.

You have a good point. I had been thinking of a model where permissions where set per app, but that isn't how Cuttlefish works.

Would it be feasible to simply note that for now a viable workaround is to have a separate team for every separate permissions domain (which in my example would mean that every app has its own team), and perhaps raise a new Feature Request to allow for per-app permissions down the line?

**Comment by mlandauer** [comment]
Yup a workaround for the time being would be to have a seperate team for each app. The main hassle I think would be that if you wanted to have access to seperate teams you would need to create a seperate login for each team as currently an admin can not be a member of multiple teams.

Also, please do raise a new issue for the per-app permissions.

**Comment by mlandauer** [comment]
Related to #159

**Comment by mlandauer** [comment]
Work in progress for the fix is in https://github.com/mlandauer/cuttlefish/tree/feature-multiple-apps-per-domain. The approach I'm planning to take is to change the DKIM "selector"* to something like `#{app_name}-#{id}.cuttlefish` whereas currently it's always `cuttlefish`. This basically leaves the core logic of how DKIM works on Cuttlefish unchanged. However, there will be extra complexity in handling the switch from the old selector to the new selector because I really don't want to force all the apps to be switched over immediately. That would be a pain.

* The DKIM selector for a domain foo.com is the prefix to the TXT record with the public key that is added which is currently `cuttlefish._domainkey.foo.com`. When an email is sent the email is signed and it says which selector was used for the signing.
